---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  # - npm install -g codeclimate-test-reporter
  # - npm install -g istanbul
  # - npm install -g mocha
  - npm install
  - bower install

script:
  - npm test

# after_success:
  # - istanbul cover _mocha -- -R spec ./tests/unit/components/*.js
  # - codeclimate < ./lcov.info
